### ISSUE TITLE
Rename platform/aspeed-ast2500evb to ast2500evb

### ISSUE THREAD

**Issue by osresearch** [u-root/u-bmc#203]
It is inconsistent and the matching `as` between `aspeed-` and the `ast2400` directories frustrates my tab completion.

**Comment by bluecmd** [comment]
Currently the platforms are named $vendor-$model-$variant. Optimizing for tab completion is an interesting idea, but in that case I'd move all socs to platform/soc/ probably

**Comment by MDr164** [comment]
platform and soc have been separated now so we can stick to $vendor-$model-$variant without any tab completion issues
