### ISSUE TITLE
Wishlist: Graphical interface for gpiowatcher

### ISSUE THREAD

**Issue by bluecmd** [u-root/u-bmc#26]
I've been thinking that having a way to stream events over console and render it graphically (like how logic analysers do) would be really nice when porting new boards.

**Comment by rjoleary** [comment]
I wonder if you can make a server which parses /dev/ttyUSB0 (or whichever device) and coverts to one of the formats accepted by [prometheus](https://prometheus.io/).

**Comment by bluecmd** [comment]
While prometheus is a sampled system made for way higher sample rates, that did give me an idea. We could be using InfluxDB (which is event based rather than sampled) to allow for either local capture and processing, and also offer a super-simple cloud version where you just run gpiowatcher and it streams all the state changes to InfluxDB. Interesting.

**Comment by bluecmd** [comment]
Unlikely to happen any time soon, re-open if needed down the road.
