### ISSUE TITLE
Something is amiss with vendoring

### ISSUE THREAD

**Issue by rjoleary** [u-root/u-bmc#29]
This is when it's building the busybox:

```
cmds/uinit/grpc.go:40:36: cannot use g (type *"google.golang.org/grpc".Server) as type *"github.com/u-root/u-bmc/vendor/google.golang.org/grpc".Server in argument to bmc.RegisterManagementServiceServer
, exit status 2
```

Looks like a vendoring issue.

**Comment by hugelgupf** [comment]
This is weird. I'll look into it. There's a lot we need to fix around vendoring, and we should discuss whether we should just go all in on modules or fix vendoring.

**Comment by bluecmd** [comment]
This should not be happening any more
