### ISSUE TITLE
Persistent RTC across reboots

### ISSUE THREAD

**Issue by bluecmd** [u-root/u-bmc#70]
The ast2400 has an RTC built-in that is not battery backed up, but using it to carry time across restarts would be a nice reliability addition to allow less RPC downtime on reboots.

**Comment by bluecmd** [comment]
@shenki This is what I want the Aspeed RTC patch for :-)

**Comment by shenki** [comment]
The openbmc dev-4.18 tree now has the rtc driver as of https://github.com/openbmc/linux/commit/df85b29a20fc9d3f2fc6dad70575c8d920533735. You can enable it in your dts with:

```
&rtc {
    status = "okay";
};
```

I've also submitted it upstream for inclusion in 4.20:

https://patchwork.ozlabs.org/patch/978323/
https://patchwork.ozlabs.org/patch/978324/
