### ISSUE TITLE
Build prerequistes

### ISSUE THREAD

**Issue by osresearch** [u-root/u-bmc#8]
Both `arm-none-eabi-gcc` and `arm-linux-gnueabi-gcc` are required.

**Comment by osresearch** [comment]
go version 1.10 or newer is required.

the tree should be checked out into a specific directory `go/src/github.com/u-root/u-bmc` or something to avoid go issues.

**Comment by rjoleary** [comment]
Also `mkimage` it seems which can be gotten from `u-boot-tools`.

**Comment by rjoleary** [comment]
I've captured all these prereqs in #15

**Comment by rjoleary** [comment]
Done!
