### ISSUE TITLE
Clean checkout fails due to git submodules

### ISSUE THREAD

**Issue by osresearch** [u-root/u-bmc#9]
There is no `u-root/Makefile`, so a clean checkout fails on the first `make -C u-root` step.

**Comment by osresearch** [comment]
Instructions should mention the need to do a `git submodule init && git submodule update`.

The path to the `openbmc/linux` tree also assumes an ssh key at github; the https repo should be used instead.

**Comment by rjoleary** [comment]
The Linux kernel takes forever to build, so we also need to check it out with `--depth=1`.

**Comment by rjoleary** [comment]
Git submodules is being difficult. I think we should have a `make depedencies` command.

**Comment by rjoleary** [comment]
If we pin the kernel release to a tag rather than a commit hash, we could use something like this in the makefile:

```
git clone --depth=1 --branch=v4.17 https://github.com/openbmc/linux.git
```

**Comment by bluecmd** [comment]
Linux does take a long time to check out, but you can also download a snapshot if you want like what circleci does - so I don't think this is a huge issue right now.
